name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version (sample 1.0.0)"
        required: true

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    env:
      ROOT: Assets/HistoryViewer
    steps:
      - uses: actions/checkout@v3
      - name: get package
        id: package
        run: |
          echo "data=$(cat ${{ env.ROOT }}/package.json | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: check tag
        id: check_tag
        run: git fetch origin "${{ env.TAG }}"
        continue-on-error: true
        env:
          TAG: release-${{ fromJson(steps.package.outputs.data).version }}

      - name: Exit if already exisists.
        if: fromJson(steps.package.outputs.data).version == inputs.version
        run: |
          echo "::notice:: Tag ${{ env.TAG }} is already exists."
          exit 1
        env:
          TAG: release-${{ fromJson(steps.package.outputs.data).version }}

      - name: set version & git commit
        run: |
          sed -i -e "s/\(\"version\":\) \"\(.*\)\",/\1 \"${{ inputs.version }}\",/" ${{ env.ROOT }}/package.json
          git add .
          git config --global user.name 'github-bot'
          git config --global user.email 'github-bot@users.noreply.github.com'
          git commit -m "update version ${{ inputs.version }}"
          git push origin main

      - name: get git commit
        id: commit
        run: |
          echo "data=$(git log --pretty='%h %s' -1)" >> $GITHUB_OUTPUT

      - name: prepare release
        run: |
          git subtree split -P "${{ env.ROOT }}" -b "${{ env.BRANCH }}"
          git checkout "${{ env.BRANCH }}"
          # git push -f origin "${{ env.BRANCH }}"
        env:
          BRANCH: release-tmp

      - name: add branch
        run: |
          git fetch
          git reset --soft origin/release
          git checkout release
          git config --global user.name 'github-bot'
          git config --global user.email 'github-bot@users.noreply.github.com'
          git commit -am "release-${{ inputs.version }}" -m "${{ steps.commit.outputs.data }}"
          git status
          git push origin release

      - name: add tag
        run: |
          git tag -f ${{ env.TAG }}
          git push -f origin ${{ env.TAG }}
        env:
          TAG: release-${{ inputs.version }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ inputs.version }}
          name: v${{ inputs.version }}
          body: https://github.com/negi0109/unity-history-viewer.git#release-${{ inputs.version }}
          draft: false
          prerelease: false
